/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import bean.ClbProduto;
import bean.ClbVendas;
import bean.ClbVendasProduto;
import dao.ProdutoDAO;
import dao.VendasProdutoDAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author DELL
 */
public class JDlgIncluirAlterarProduto extends javax.swing.JDialog {
    public JDlgVendas jDlgVendas;
    ProdutoDAO produtoDAO;
    ClbProduto clbProduto;
    ClbVendasProduto clbVendasProduto;
    VendasProdutoDAO vendasProdutoDAO;
    ClbVendas clbVendas;


    /**
     * Creates new form JDlgCadastroProduto
     */
    public JDlgIncluirAlterarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        /*if (jDlgVendas.incluindo == true){
            setTitle("Inclusão de Produtos");
        }else{
            setTitle("Alteração de Produtos");
        }*/
        
        setTitle("Inclusão ou Alteração de Produtos");
        setLocationRelativeTo(null);
        
        //desabilitar();
        Util.habilitar(true, jCboClb_Produto, jTxtClb_Quantidade, jTxtClb_ValorUnitario, jBtnClb_Ok, jBtnClb_Cancelar ); //habilita os campos
        Util.habilitar(false, jTxtClb_Total);//desabilita os campos
        
        produtoDAO = new ProdutoDAO();
        List listaNomeProd = produtoDAO.listAll();
        for (int i = 0; i < listaNomeProd.size(); i++){
            jCboClb_Produto.addItem(((ClbProduto) listaNomeProd.get(i)));
        }
        
    }
    
    /*public void desabilitar(){
        //desabilita os campos e botoes que não tem a necessidade de aparecer 
        jTxtClb_Total.setEnabled(false);
        
        jTxtClb_Quantidade.setEnabled(true);
        jTxtClb_ValorUnitario.setEnabled(true);
        jBtnClb_Ok.setEnabled(true);
        jBtnClb_Cancelar.setEnabled(true);
        
    }*/
    
    public void setTelaAnterior(JDlgVendas jDlgVendas){
        this.jDlgVendas = jDlgVendas;
    }
    
   public ClbVendasProduto viewBean(){
        clbVendasProduto = new ClbVendasProduto();
        
        //pega oq esta na tela e joga para o bean
        
        /*ClbProduto produto1 = (ClbProduto) jCboClb_Produto.getSelectedItem();
        clbVendasProduto.setClbProduto(produto1.getClbIdproduto()); //converter para int */
      
        ClbProduto produto1 = ((ClbProduto) jCboClb_Produto.getSelectedItem());
        clbVendasProduto.setClbProduto(produto1); 
        
        return clbVendasProduto; //
    }
    
    public void beanView(ClbVendasProduto clbVendasProduto){//pega do bean e joga na tela -- o parametro é o bean
        //mostrar na tela os dados
        
        /*int idProduto = clbVendasProduto.getClbProduto();
        vendasProdutoDAO = new VendasProdutoDAO();
        jCboClb_Produto.setSelectedItem(vendasProdutoDAO.list(idProduto));*/
        
        jCboClb_Produto.setSelectedItem(clbVendasProduto.getClbProduto());
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jCboClb_Produto = new javax.swing.JComboBox<ClbProduto>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtClb_Quantidade = new javax.swing.JTextField();
        jTxtClb_ValorUnitario = new javax.swing.JTextField();
        jTxtClb_Total = new javax.swing.JTextField();
        jBtnClb_Ok = new javax.swing.JButton();
        jBtnClb_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Produto: ");

        jCboClb_Produto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboClb_ProdutoItemStateChanged(evt);
            }
        });

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Valor Unitário:");

        jLabel4.setText("Total:");

        jTxtClb_Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtClb_QuantidadeActionPerformed(evt);
            }
        });
        jTxtClb_Quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtClb_QuantidadeKeyReleased(evt);
            }
        });

        jTxtClb_ValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtClb_ValorUnitarioKeyReleased(evt);
            }
        });

        jTxtClb_Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtClb_TotalActionPerformed(evt);
            }
        });

        jBtnClb_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar.png"))); // NOI18N
        jBtnClb_Ok.setText("OK");
        jBtnClb_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClb_OkActionPerformed(evt);
            }
        });

        jBtnClb_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnClb_Cancelar.setText("Cancelar");
        jBtnClb_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClb_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnClb_Ok)
                            .addGap(18, 18, 18)
                            .addComponent(jBtnClb_Cancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jTxtClb_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtClb_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtClb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))))
                    .addComponent(jCboClb_Produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCboClb_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtClb_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtClb_ValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtClb_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClb_Cancelar)
                    .addComponent(jBtnClb_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtClb_QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtClb_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtClb_QuantidadeActionPerformed

    private void jBtnClb_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClb_OkActionPerformed
        // TODO add your handling code here:
        clbVendasProduto = new ClbVendasProduto();
        clbVendasProduto.setClbProduto((ClbProduto) jCboClb_Produto.getSelectedItem()); //pega o bean do comboBox
        clbVendasProduto.setClbQuantidade(Util.strInt(jTxtClb_Quantidade.getText())); //pega o valor do campo de quantidade e tranforma de string em int
        clbVendasProduto.setClbValorUnitario(Double.parseDouble(jTxtClb_ValorUnitario.getText())); //(Util.strDouble(jTxtClb_ValorUnitario.getText())); ////pega o valor do campo de valorUni e tranforma de string em double
        
        //Nesse if ele fara a verifcação do tipo de operação que a teça deve fazer sendo INCLUSÃO ou ALTERAÇÃO
        //Essa verificação ocorrera de acordo com o titulo da tela 
        //para isso começa deixando todo o Titulo em CAIXA-ALTA(MAIUSCULAS), aasim, verifica se 
        //a primeira letra do Title é "I", se for então é uma INCLUSÃO, se NÃO FOR é uma ALTERAÇÃO
        if(getTitle().toUpperCase().substring(0, 1).equals("I")){
            //utitiliza os metodos de adicionar que criamos na tela Controller
            jDlgVendas.vendasProdutoController.addBean(clbVendasProduto);
        }else{
            //utiliza o metodo alterar que criamos na tela controller, 
            //para isso pega a linha selecionada na tabela e substitui o bean
            jDlgVendas.vendasProdutoController.updateBean(jDlgVendas.getSelectedRowProd(), clbVendasProduto);
        }
        
        setVisible(false); //fecha a tela 
       
    }//GEN-LAST:event_jBtnClb_OkActionPerformed

    private void jTxtClb_TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtClb_TotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtClb_TotalActionPerformed

    private void jBtnClb_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClb_CancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnClb_CancelarActionPerformed

    private void jCboClb_ProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboClb_ProdutoItemStateChanged
        // TODO add your handling code here:
        jTxtClb_Quantidade.setText("1"); //começa a quantidade dos produtos em 1
        clbProduto = (ClbProduto) jCboClb_Produto.getSelectedItem(); //pega o bean do comboBox
        jTxtClb_ValorUnitario.setText(Util.doubleStr(clbProduto.getClbPreco())); //converte o bean com o preço e passa ele para o campo de valor unitario
        jTxtClb_Total.setText(jTxtClb_ValorUnitario.getText()); //começa o valor do total de acordo com o valor de 1 produto
        
    }//GEN-LAST:event_jCboClb_ProdutoItemStateChanged

    private void jTxtClb_QuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClb_QuantidadeKeyReleased
        // TODO add your handling code here:
        if(jTxtClb_Quantidade.getText().isEmpty() == false){ //se o campo de quantidade não estiver vazio
            //utilizei a conversão de Double pq o Util dava com conversão incorreta de string para double
            double valorUnitario = (Double.parseDouble(jTxtClb_ValorUnitario.getText()));//Util.strDouble(jTxtClb_ValorUnitario.getText());
            double quantidade = (Double.parseDouble(jTxtClb_Quantidade.getText())); //Util.strDouble(jTxtClb_Quantidade.getText());
            jTxtClb_Total.setText(Util.doubleStr(quantidade * valorUnitario));
        }else{
            jTxtClb_Total.setText("0"); //mostra o valor zero no campo Total
        }
    }//GEN-LAST:event_jTxtClb_QuantidadeKeyReleased

    private void jTxtClb_ValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClb_ValorUnitarioKeyReleased
        // TODO add your handling code here:
       if(jTxtClb_ValorUnitario.getText().isEmpty() == false){ //se o campo de quantidade não estiver vazio
            double valorUnitario = (Double.parseDouble(jTxtClb_ValorUnitario.getText()));//Util.strDouble(jTxtClb_ValorUnitario.getText());
            double quantidade = (Double.parseDouble(jTxtClb_Quantidade.getText())); //Util.strDouble(jTxtClb_Quantidade.getText());
            jTxtClb_Total.setText(Util.doubleStr(quantidade * valorUnitario));
        }else{
            jTxtClb_Total.setText("0"); //mostra o valor zero no campo Total
        }
    }//GEN-LAST:event_jTxtClb_ValorUnitarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgIncluirAlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgIncluirAlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgIncluirAlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgIncluirAlterarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgIncluirAlterarProduto dialog = new JDlgIncluirAlterarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClb_Cancelar;
    private javax.swing.JButton jBtnClb_Ok;
    private javax.swing.JComboBox<ClbProduto> jCboClb_Produto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTxtClb_Quantidade;
    private javax.swing.JTextField jTxtClb_Total;
    private javax.swing.JTextField jTxtClb_ValorUnitario;
    // End of variables declaration//GEN-END:variables
}
