/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author DELL
 */
public class JFrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrmLogin
     */
    public JFrmLogin() {
        initComponents();
        setTitle("Login de Usuários");
        setLocationRelativeTo(null);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtLoginUsuario = new javax.swing.JTextField();
        jPwfLoginSenha = new javax.swing.JPasswordField();
        jBtnLoginAcessar = new javax.swing.JButton();
        jBtnLoginCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuário:");

        jLabel2.setText("Senha:");

        jTxtLoginUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtLoginUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtLoginUsuarioFocusLost(evt);
            }
        });

        jPwfLoginSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPwfLoginSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPwfLoginSenhaFocusLost(evt);
            }
        });
        jPwfLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwfLoginSenhaActionPerformed(evt);
            }
        });

        jBtnLoginAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controle-de-acesso (2).png"))); // NOI18N
        jBtnLoginAcessar.setText("Acessar");
        jBtnLoginAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginAcessarActionPerformed(evt);
            }
        });

        jBtnLoginCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnLoginCancelar.setText("Cancelar");
        jBtnLoginCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginCancelarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jTxtLoginUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(jPwfLoginSenha)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBtnLoginAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnLoginCancelar)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(jPwfLoginSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnLoginAcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLoginCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginAcessarActionPerformed
        // TODO add your handling code here:
        //quando clicar em acessar devesse entrar no JFrmPrincipal e ter acesso ao sistema
        
        // login antigo
        if(jTxtLoginUsuario.getText().equals("barrios") && jPwfLoginSenha.getText().equals("senha123")){
            JFrmPrincipal jFrmPrincipal = new JFrmPrincipal();
            jFrmPrincipal.setVisible(true);
            //JOptionPane.showMessageDialog(null , "Deu certo");
        } else if(jTxtLoginUsuario.getText().equals("livraria") && jPwfLoginSenha.getText().equals("senha456")){
            JFrmPrincipal jFrmPrincipal = new JFrmPrincipal();
            jFrmPrincipal.setVisible(true);
            //JOptionPane.showMessageDialog(null , "Logado");
        } else {
            JOptionPane.showMessageDialog(null , "Usuario ou senha incorretos");
           
        }
        
        Util.limparCampos();
         
        

    }//GEN-LAST:event_jBtnLoginAcessarActionPerformed

    private void jTxtLoginUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtLoginUsuarioFocusGained
        // TODO add your handling code here:
        jTxtLoginUsuario.setBackground(Color.lightGray);
    }//GEN-LAST:event_jTxtLoginUsuarioFocusGained

    private void jTxtLoginUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtLoginUsuarioFocusLost
        // TODO add your handling code here:
        jTxtLoginUsuario.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtLoginUsuarioFocusLost

    private void jPwfLoginSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPwfLoginSenhaFocusGained
        // TODO add your handling code here:
        jPwfLoginSenha.setBackground(Color.lightGray);
    }//GEN-LAST:event_jPwfLoginSenhaFocusGained

    private void jPwfLoginSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPwfLoginSenhaFocusLost
        // TODO add your handling code here:
        jPwfLoginSenha.setBackground(Color.WHITE);
    }//GEN-LAST:event_jPwfLoginSenhaFocusLost

    private void jBtnLoginCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBtnLoginCancelarActionPerformed

    private void jPwfLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwfLoginSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwfLoginSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoginAcessar;
    private javax.swing.JButton jBtnLoginCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPwfLoginSenha;
    private javax.swing.JTextField jTxtLoginUsuario;
    // End of variables declaration//GEN-END:variables
}
