/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package query;


import bean.ClbCliente;
import dao.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import view.ClienteController;

/**
 *
 * @author DELL
 */
public class JDlgConsultaCliente extends javax.swing.JDialog {
    private ClienteController clienteController; //global a classe
    ClienteDAO clienteDAO;
    
    /**
     * Creates new form JDlgConsultaUsuario
     */
    public JDlgConsultaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consulta de Cliente");
        clienteDAO = new ClienteDAO(); //criou o objeto usuarios_DAO
        clienteController = new ClienteController(); //criei o usuarios controle   
        
        jCboClb_EstadoCivil.setSelectedIndex(-1); //começa vazio o comboBox
        List lista = clienteDAO.listAll();
        clienteController.setList(lista); //passando o a lista para o usuariosControle -> se retorna a lista para que as informações sejam mostradas e a lista vem do Usuarios_DAO
        jTable1.setModel(clienteController); //agora o usuariosControle que controla a tabela
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtClb_Nome = new javax.swing.JTextField();
        jBtnClb_Consultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCboClb_EstadoCivil = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        jBtnClb_Consultar.setText("Consultar");
        jBtnClb_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClb_ConsultarActionPerformed(evt);
            }
        });

        jLabel2.setText("Estado Cívil:");

        jCboClb_EstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro(a)", "Casado(a)", "Separado(a)", "Divorciado(a)", "Víuvo(a)", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtClb_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCboClb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnClb_Consultar)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnClb_Consultar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtClb_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboClb_EstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClb_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClb_ConsultarActionPerformed
        // TODO add your handling code here:
        
        
        if(jTxtClb_Nome.getText().equals("") && jCboClb_EstadoCivil.getSelectedIndex() ==-1){
            List lista = clienteDAO.listAll();
            clienteController.setList(lista);
        }else{
            if(!jTxtClb_Nome.getText().equals("") && (jCboClb_EstadoCivil.getSelectedIndex() !=-1)){
                List lista = clienteDAO.listNomeEstado(jTxtClb_Nome.getText(), (int) jCboClb_EstadoCivil.getSelectedIndex());
                clienteController.setList(lista);
            }else{
                if(! jTxtClb_Nome.getText().equals("")){
                    List lista = clienteDAO.listNome(jTxtClb_Nome.getText()); //Criou uma lista e ta passando o metodo ListAll do Usuarios_DAO
                    clienteController.setList(lista); //passando o a lista para o usuariosControle -> se retorna a lista para que as informações sejam mostradas e a lista vem do Usuarios_DAO
            }else{
                if(jCboClb_EstadoCivil.getSelectedIndex() !=-1){
                    List lista = clienteDAO.listEstadoCivil((int) jCboClb_EstadoCivil.getSelectedIndex()); //Criou uma lista e ta passando o metodo ListAll do Usuarios_DAO
                    clienteController.setList(lista); //passando o a lista para o usuariosControle -> se retorna a lista para que as informações sejam mostradas e a lista vem do Usuarios_DAO
                    }
                }
            }
        }
        
        /*ArrayList lista; //para valer´para tudo
        if(jTxtClb_Nome.getText().equals("") && jCboClb_EstadoCivil.getSelectedIndex() ==-1){
            lista = (ArrayList) clienteDAO.listAll();
            clienteController.setList(lista);
        }else{
            if(!jTxtClb_Nome.getText().equals("") && (jCboClb_EstadoCivil.getSelectedIndex() !=-1)){
                lista = (ArrayList) clienteDAO.listNomeEstado(jTxtClb_Nome.getText(), (int) jCboClb_EstadoCivil.getSelectedItem());
                clienteController.setList(lista);
            }else{
                if(! jTxtClb_Nome.getText().equals("")){
                    lista = (ArrayList) clienteDAO.listNome(jTxtClb_Nome.getText()); //Criou uma lista e ta passando o metodo ListAll do Usuarios_DAO
                    clienteController.setList(lista); //passando o a lista para o usuariosControle -> se retorna a lista para que as informações sejam mostradas e a lista vem do Usuarios_DAO
            }else{
                if(jCboClb_EstadoCivil.getSelectedIndex() !=-1){
                    lista = (ArrayList) clienteDAO.listEstadoCivil((int) jCboClb_EstadoCivil.getSelectedItem()); //Criou uma lista e ta passando o metodo ListAll do Usuarios_DAO
                    clienteController.setList(lista); //passando o a lista para o usuariosControle -> se retorna a lista para que as informações sejam mostradas e a lista vem do Usuarios_DAO
                    }
                }
            }
        }*/
        
        
    }//GEN-LAST:event_jBtnClb_ConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaCliente dialog = new JDlgConsultaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClb_Consultar;
    private javax.swing.JComboBox<String> jCboClb_EstadoCivil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtClb_Nome;
    // End of variables declaration//GEN-END:variables
}
