package bean;
// Generated 14/09/2023 08:05:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClbCliente generated by hbm2java
 */
@Entity
@Table(name="clb_cliente"
    ,catalog="db_camilly_barrios"
)
public class ClbCliente  implements java.io.Serializable {


     private int clbIdcliente;
     private String clbNome;
     private String clbTelefone;
     private String clbCpf;
     private String clbRg;
     private int clbSexo;
     private Date clbDataNascimento;
     private String clbEmail;
     private String clbCep;
     private String clbEndereco;
     private String clbBairro;
     private String clbCidade;
     private int clbEstadoCivil;
     private int clbComposicaoFamiliar;
     private double clbRenda;
    

    public ClbCliente() {
    }

	
    public ClbCliente(String clbNome, String clbTelefone, String clbCpf, String clbRg, Date clbDataNascimento, String clbEmail, String clbCep, String clbEndereco, String clbBairro, String clbCidade, int clbEstadoCivil, int clbComposicaoFamiliar, double clbRenda) {
        this.clbNome = clbNome;
        this.clbTelefone = clbTelefone;
        this.clbCpf = clbCpf;
        this.clbRg = clbRg;
        this.clbDataNascimento = clbDataNascimento;
        this.clbEmail = clbEmail;
        this.clbCep = clbCep;
        this.clbEndereco = clbEndereco;
        this.clbBairro = clbBairro;
        this.clbCidade = clbCidade;
        this.clbEstadoCivil = clbEstadoCivil;
        this.clbComposicaoFamiliar = clbComposicaoFamiliar;
        this.clbRenda = clbRenda;
    }
    public ClbCliente(String clbNome, String clbTelefone, String clbCpf, String clbRg, int clbSexo, Date clbDataNascimento, String clbEmail, String clbCep, String clbEndereco, String clbBairro, String clbCidade, int clbEstadoCivil, int clbComposicaoFamiliar, double clbRenda) {
       this.clbNome = clbNome;
       this.clbTelefone = clbTelefone;
       this.clbCpf = clbCpf;
       this.clbRg = clbRg;
       this.clbSexo = clbSexo;
       this.clbDataNascimento = clbDataNascimento;
       this.clbEmail = clbEmail;
       this.clbCep = clbCep;
       this.clbEndereco = clbEndereco;
       this.clbBairro = clbBairro;
       this.clbCidade = clbCidade;
       this.clbEstadoCivil = clbEstadoCivil;
       this.clbComposicaoFamiliar = clbComposicaoFamiliar;
       this.clbRenda = clbRenda;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clb_idcliente", unique=true, nullable=false)
    public int getClbIdcliente() {
        return this.clbIdcliente;
    }
    
    public void setClbIdcliente(int clbIdcliente) {
        this.clbIdcliente = clbIdcliente;
    }

    
    @Column(name="clb_nome", nullable=false, length=100)
    public String getClbNome() {
        return this.clbNome;
    }
    
    public void setClbNome(String clbNome) {
        this.clbNome = clbNome;
    }

    
    @Column(name="clb_telefone", nullable=false, length=14)
    public String getClbTelefone() {
        return this.clbTelefone;
    }
    
    public void setClbTelefone(String clbTelefone) {
        this.clbTelefone = clbTelefone;
    }

    
    @Column(name="clb_cpf", nullable=false, length=14)
    public String getClbCpf() {
        return this.clbCpf;
    }
    
    public void setClbCpf(String clbCpf) {
        this.clbCpf = clbCpf;
    }

    
    @Column(name="clb_rg", nullable=false, length=10)
    public String getClbRg() {
        return this.clbRg;
    }
    
    public void setClbRg(String clbRg) {
        this.clbRg = clbRg;
    }

    
    @Column(name="clb_sexo")
    public int getClbSexo() {
        return this.clbSexo;
    }
    
    public void setClbSexo(int clbSexo) {
        this.clbSexo = clbSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clb_dataNascimento", nullable=false, length=10)
    public Date getClbDataNascimento() {
        return this.clbDataNascimento;
    }
    
    public void setClbDataNascimento(Date clbDataNascimento) {
        this.clbDataNascimento = clbDataNascimento;
    }

    
    @Column(name="clb_email", nullable=false, length=50)
    public String getClbEmail() {
        return this.clbEmail;
    }
    
    public void setClbEmail(String clbEmail) {
        this.clbEmail = clbEmail;
    }

    
    @Column(name="clb_cep", nullable=false, length=9)
    public String getClbCep() {
        return this.clbCep;
    }
    
    public void setClbCep(String clbCep) {
        this.clbCep = clbCep;
    }

    
    @Column(name="clb_endereco", nullable=false, length=50)
    public String getClbEndereco() {
        return this.clbEndereco;
    }
    
    public void setClbEndereco(String clbEndereco) {
        this.clbEndereco = clbEndereco;
    }

    
    @Column(name="clb_bairro", nullable=false, length=45)
    public String getClbBairro() {
        return this.clbBairro;
    }
    
    public void setClbBairro(String clbBairro) {
        this.clbBairro = clbBairro;
    }

    
    @Column(name="clb_cidade", nullable=false, length=45)
    public String getClbCidade() {
        return this.clbCidade;
    }
    
    public void setClbCidade(String clbCidade) {
        this.clbCidade = clbCidade;
    }

    
    @Column(name="clb_estadoCivil", nullable=false)
    public int getClbEstadoCivil() {
        return this.clbEstadoCivil;
    }
    
    public void setClbEstadoCivil(int clbEstadoCivil) {
        this.clbEstadoCivil = clbEstadoCivil;
    }

    
    @Column(name="clb_composicaoFamiliar", nullable=false)
    public int getClbComposicaoFamiliar() {
        return this.clbComposicaoFamiliar;
    }
    
    public void setClbComposicaoFamiliar(int clbComposicaoFamiliar) {
        this.clbComposicaoFamiliar = clbComposicaoFamiliar;
    }

    
    @Column(name="clb_renda", nullable=false, precision=10)
    public double getClbRenda() {
        return this.clbRenda;
    }
    
    public void setClbRenda(double clbRenda) {
        this.clbRenda = clbRenda;
    }
    
    //problema: o metodo toString, não recebe tipos de object e int 
    @Override
    public String toString(){
        return this.clbNome;
    }
    
    
    @Override
    public boolean equals(Object object){
        if(object instanceof ClbCliente){
            ClbCliente clbCliente = (ClbCliente) object;
            if(this.getClbIdcliente() == clbCliente.getClbIdcliente()){
                return true;
            }
        }
        return false;
    }




}


