package bean;
// Generated 14/09/2023 08:05:16 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClbUsuario generated by hbm2java
 */
@Entity
@Table(name="clb_usuario"
    ,catalog="db_camilly_barrios"
)
public class ClbUsuario  implements java.io.Serializable {


     private int clbIdusuario;
     private String clbNomeUsuario;
     private String clbApelidoUsuario;
     private Date clbDataNascimento;
     private String clbCpf;
     private String clbSenha;
     private int clbNivel;
     private String clbAtivo;

    public ClbUsuario() {
    }

    public ClbUsuario(String clbNomeUsuario, String clbApelidoUsuario, Date clbDataNascimento, String clbCpf, String clbSenha, int clbNivel, String clbAtivo) {
       this.clbNomeUsuario = clbNomeUsuario;
       this.clbApelidoUsuario = clbApelidoUsuario;
       this.clbDataNascimento = clbDataNascimento;
       this.clbCpf = clbCpf;
       this.clbSenha = clbSenha;
       this.clbNivel = clbNivel;
       this.clbAtivo = clbAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clb_idusuario", unique=true, nullable=false)
    public int getClbIdusuario() {
        return this.clbIdusuario;
    }
    
    public void setClbIdusuario(int clbIdusuario) {
        this.clbIdusuario = clbIdusuario;
    }

    
    @Column(name="clb_nomeUsuario", nullable=false, length=100)
    public String getClbNomeUsuario() {
        return this.clbNomeUsuario;
    }
    
    public void setClbNomeUsuario(String clbNomeUsuario) {
        this.clbNomeUsuario = clbNomeUsuario;
    }

    
    @Column(name="clb_apelidoUsuario", nullable=false, length=20)
    public String getClbApelidoUsuario() {
        return this.clbApelidoUsuario;
    }
    
    public void setClbApelidoUsuario(String clbApelidoUsuario) {
        this.clbApelidoUsuario = clbApelidoUsuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clb_dataNascimento", nullable=false, length=10)
    public Date getClbDataNascimento() {
        return this.clbDataNascimento;
    }
    
    public void setClbDataNascimento(Date clbDataNascimento) {
        this.clbDataNascimento = clbDataNascimento;
    }

    
    @Column(name="clb_cpf", nullable=false, length=14)
    public String getClbCpf() {
        return this.clbCpf;
    }
    
    public void setClbCpf(String clbCpf) {
        this.clbCpf = clbCpf;
    }

    
    @Column(name="clb_senha", nullable=false, length=20)
    public String getClbSenha() {
        return this.clbSenha;
    }
    
    public void setClbSenha(String clbSenha) {
        this.clbSenha = clbSenha;
    }

    
    @Column(name="clb_nivel", nullable=false)
    public int getClbNivel() {
        return this.clbNivel;
    }
    
    public void setClbNivel(int clbNivel) {
        this.clbNivel = clbNivel;
    }

    
    @Column(name="clb_ativo", nullable=false, length=1)
    public String getClbAtivo() {
        return this.clbAtivo;
    }
    
    public void setClbAtivo(String clbAtivo) {
        this.clbAtivo = clbAtivo;
    }




}


