package bean;
// Generated 14/09/2023 08:05:16 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClbVendasProduto generated by hbm2java
 */
@Entity
@Table(name="clb_vendas_produto"
    ,catalog="db_camilly_barrios"
)
public class ClbVendasProduto  implements java.io.Serializable {


     private int clbIdvendasProduto;
     private ClbProduto clbProduto;
     private ClbVendas clbVendas;
     private int clbQuantidade;
     private double clbValorUnitario;

    public ClbVendasProduto() {
    }

    public ClbVendasProduto(ClbProduto clbProduto, ClbVendas clbVendas, int clbQuantidade, double clbValorUnitario) {
       this.clbProduto = clbProduto;
       this.clbVendas = clbVendas;
       this.clbQuantidade = clbQuantidade;
       this.clbValorUnitario = clbValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clb_idvendas_produto", unique=true, nullable=false)
    public int getClbIdvendasProduto() {
        return this.clbIdvendasProduto;
    }
    
    public void setClbIdvendasProduto(int clbIdvendasProduto) {
        this.clbIdvendasProduto = clbIdvendasProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clb_produto", nullable=false)
    public ClbProduto getClbProduto() {
        return this.clbProduto;
    }
    
    public void setClbProduto(ClbProduto clbProduto) {
        this.clbProduto = clbProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clb_vendas", nullable=false)
    public ClbVendas getClbVendas() {
        return this.clbVendas;
    }
    
    public void setClbVendas(ClbVendas clbVendas) {
        this.clbVendas = clbVendas;
    }

    
    @Column(name="clb_quantidade", nullable=false)
    public int getClbQuantidade() {
        return this.clbQuantidade;
    }
    
    public void setClbQuantidade(int clbQuantidade) {
        this.clbQuantidade = clbQuantidade;
    }

    
    @Column(name="clb_valorUnitario", nullable=false, precision=10)
    public double getClbValorUnitario() {
        return this.clbValorUnitario;
    }
    
    public void setClbValorUnitario(double clbValorUnitario) {
        this.clbValorUnitario = clbValorUnitario;
    }




}


