package bean;
// Generated 14/09/2023 08:05:16 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClbVendedor generated by hbm2java
 */
@Entity
@Table(name="clb_vendedor"
    ,catalog="db_camilly_barrios"
)
public class ClbVendedor  implements java.io.Serializable {


     private int clbIdvendedor;
     private String clbNomeVendedor;
     private String clbTelefone;
     private Date clbDataNascimento;
     private String clbCpf;
     private String clbRg;
     private int clbSexo;
     private String clbEmail;
     private double clbSalario;
     

    public ClbVendedor() {
    }

	
    public ClbVendedor(String clbNomeVendedor, String clbTelefone, Date clbDataNascimento, String clbCpf, String clbRg, String clbEmail, double clbSalario) {
        this.clbNomeVendedor = clbNomeVendedor;
        this.clbTelefone = clbTelefone;
        this.clbDataNascimento = clbDataNascimento;
        this.clbCpf = clbCpf;
        this.clbRg = clbRg;
        this.clbEmail = clbEmail;
        this.clbSalario = clbSalario;
    }
    public ClbVendedor(String clbNomeVendedor, String clbTelefone, Date clbDataNascimento, String clbCpf, String clbRg, int clbSexo, String clbEmail, double clbSalario) {
       this.clbNomeVendedor = clbNomeVendedor;
       this.clbTelefone = clbTelefone;
       this.clbDataNascimento = clbDataNascimento;
       this.clbCpf = clbCpf;
       this.clbRg = clbRg;
       this.clbSexo = clbSexo;
       this.clbEmail = clbEmail;
       this.clbSalario = clbSalario;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clb_idvendedor", unique=true, nullable=false)
    public int getClbIdvendedor() {
        return this.clbIdvendedor;
    }
    
    public void setClbIdvendedor(int clbIdvendedor) {
        this.clbIdvendedor = clbIdvendedor;
    }

    
    @Column(name="clb_nomeVendedor", nullable=false, length=100)
    public String getClbNomeVendedor() {
        return this.clbNomeVendedor;
    }
    
    public void setClbNomeVendedor(String clbNomeVendedor) {
        this.clbNomeVendedor = clbNomeVendedor;
    }

    
    @Column(name="clb_telefone", nullable=false, length=14)
    public String getClbTelefone() {
        return this.clbTelefone;
    }
    
    public void setClbTelefone(String clbTelefone) {
        this.clbTelefone = clbTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clb_dataNascimento", nullable=false, length=10)
    public Date getClbDataNascimento() {
        return this.clbDataNascimento;
    }
    
    public void setClbDataNascimento(Date clbDataNascimento) {
        this.clbDataNascimento = clbDataNascimento;
    }

    
    @Column(name="clb_cpf", nullable=false, length=14)
    public String getClbCpf() {
        return this.clbCpf;
    }
    
    public void setClbCpf(String clbCpf) {
        this.clbCpf = clbCpf;
    }

    
    @Column(name="clb_rg", nullable=false, length=10)
    public String getClbRg() {
        return this.clbRg;
    }
    
    public void setClbRg(String clbRg) {
        this.clbRg = clbRg;
    }

    
    @Column(name="clb_sexo")
    public int getClbSexo() {
        return this.clbSexo;
    }
    
    public void setClbSexo(int clbSexo) {
        this.clbSexo = clbSexo;
    }

    
    @Column(name="clb_email", nullable=false, length=50)
    public String getClbEmail() {
        return this.clbEmail;
    }
    
    public void setClbEmail(String clbEmail) {
        this.clbEmail = clbEmail;
    }

    
    @Column(name="clb_salario", nullable=false, precision=10)
    public double getClbSalario() {
        return this.clbSalario;
    }
    
    public void setClbSalario(double clbSalario) {
        this.clbSalario = clbSalario;
    }



}


