package bean;
// Generated 14/09/2023 08:05:16 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClbVendas generated by hbm2java
 */
@Entity
@Table(name="clb_vendas"
    ,catalog="db_camilly_barrios"
)
public class ClbVendas  implements java.io.Serializable {


     private int clbIdvendas;
     private ClbCliente clbCliente;
     private ClbVendedor clbVendedor;
     private Date clbDataVenda;
     private double clbValorTotal;
     

    public ClbVendas() {
    }

    public ClbVendas(ClbCliente clbCliente, ClbVendedor clbVendedor, Date clbDataVenda, double clbValorTotal) {
       this.clbCliente = clbCliente;
       this.clbVendedor = clbVendedor;
       this.clbDataVenda = clbDataVenda;
       this.clbValorTotal = clbValorTotal;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="clb_idvendas", unique=true, nullable=false)
    public int getClbIdvendas() {
        return this.clbIdvendas;
    }
    
    public void setClbIdvendas(int clbIdvendas) {
        this.clbIdvendas = clbIdvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clb_cliente")
    public ClbCliente getClbCliente() {
        return this.clbCliente;
    }
    
    public void setClbCliente(ClbCliente clbCliente) {
        this.clbCliente = clbCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clb_vendedor")
    public ClbVendedor getClbVendedor() {
        return this.clbVendedor;
    }
    
    public void setClbVendedor(ClbVendedor clbVendedor) {
        this.clbVendedor = clbVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="clb_dataVenda", length=10)
    public Date getClbDataVenda() {
        return this.clbDataVenda;
    }
    
    public void setClbDataVenda(Date clbDataVenda) {
        this.clbDataVenda = clbDataVenda;
    }

    
    @Column(name="clb_valorTotal", precision=10)
    public double getClbValorTotal() {
        return this.clbValorTotal;
    }
    
    public void setClbValorTotal(double clbValorTotal) {
        this.clbValorTotal = clbValorTotal;
    }
   




}


